### ISSUE TITLE
Attempt to replicate... Fail

### ISSUE THREAD

**Issue by zignig** [CadQuery/pywrap#10]
Tried to build.

zignig@noid:/opt/test_cq/pywrap$ ./run.sh
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/test_cq/pywrap/bindgen/__main__.py", line 95, in <module>
    main()
  File "/home/zignig/.local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/zignig/.local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/zignig/.local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/zignig/.local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/zignig/.local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/zignig/.local/lib/python3.6/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/opt/test_cq/pywrap/bindgen/__main__.py", line 29, in parse
    settings,module_mapping,module_settings = read_settings(configuration)
  File "/opt/test_cq/pywrap/bindgen/__init__.py", line 77, in read_settings
    settings = toml.load(f)
  File "/home/zignig/.local/lib/python3.6/site-packages/toml.py", line 108, in load
    return loads(f.read(), _dict)
  File "/home/zignig/.local/lib/python3.6/site-packages/toml.py", line 373, in loads
    multibackslash)
  File "/home/zignig/.local/lib/python3.6/site-packages/toml.py", line 478, in _load_line
    value, vtype = _load_value(pair[1], _dict, strictly_valid)
  File "/home/zignig/.local/lib/python3.6/site-packages/toml.py", line 608, in _load_value
    raise TomlDecodeError("Stuff after closed string. WTF?")
toml.TomlDecodeError: Stuff after closed string. WTF?

perhaps we can have a build from source ?  I don't mind waiting for a _while_ to make.

**Comment by adam-urbanczyk** [comment]
CI passes so for now I will not investigate. First thing I'd check if the environment conforms the speced one (`env.yml`).  BTW: every CI run publishes all generated files and the final module, so if you feel like you could try it out.

**Comment by zignig** [comment]
Ok, needs more investigation.
